name: Bug Report
description: Create a bug report to help improve RiseMP
# type: 'Bug' # Add back when issue types are enabled in Rise org
title: 'Bug: '
body:

  # Tip to warn of checking for existing issues
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Have you checked for similar issues? There's a possibility the bug you are experiencing has already been reported. Please do a thorough search before creating a new issue.

  # Description
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  # Step To Reproduce
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  # RiseMP Version
  - type: input
    id: rise_version
    attributes:
      label: RiseMP Version
      description: Which version of RiseMP are you using? To copy your app version, access it from Settings -> About -> Version.
      placeholder: "e.g. 0.14.0-alpha3"
    validations:
      required: true

  # Windows Version
  - type: input
    id: windows_version
    attributes:
      label: Windows Version
      description: Which version of Windows are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy.
      placeholder: "e.g. 10.0.22621.1848"
    validations:
      required: true

  # Note that the user should always upload the report rather than pasting it.
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please **upload** the log file by clicking "Attach files".
        >
        > Feel free to remove sensitive information such as your usernames or drive names.

  # Log File
  - type: textarea
    attributes:
      label: Log File
      description: |
        Please upload the log file as an attachment
      placeholder: |
        To upload the log, copy from crash window; Or
        - Drag and drop them into this text area.
    validations:
      required: true