blank_issues_enabled: false
contact_links:
#  - name: Translation issue
#    url: https://crowdin.com/project/
#    about: Help improve translations on Crowdin.
  - name: Question & Discussion
    url: https://dsc.gg/rise-software
    about: Post your questions and join the discussion. You can participate in chats on every channel.
